AbcSize:
  Exclude:
    - lib/lita/handlers/dig.rb

ClassLength:
  Max: 200

CyclomaticComplexity:
  Max: 75

PerceivedComplexity:
  Exclude:
    - lib/lita/handlers/dig.rb

Documentation:
  Exclude:
    - lib/lita/handlers/dig.rb

FileName:
  Exclude:
    - lib/lita-dig.rb

MethodLength:
  Max: 200
