require: rubocop-rspec

Documentation:
  Exclude:
    - lib/lita/handlers/dig.rb

FileName:
  Exclude:
    - lib/lita-dig.rb

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 2

Metrics/BlockLength:
  Max: 100

Gemspec/RequiredRubyVersion:
  Enabled: false
